#!/bin/bash

cd ~/Documents/Contract\ to\ Close/PDF\ Converter

echo “Starting conversion\n”
convert *.jpg FinishedPDFDocument.pdf
echo “Finished conversion\n”
echo "Deleting JPGs"
rm *.jpg
echo "Done deleting"

kill -9 $PPID
